Test/Models/StudentMealPlan.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Test.Models
{
    // a table linking students to their individual meal plans, and the meal plan table
    public class StudentMealPlan
    {
        [Key]
        public int student_meal_plan_id { get; set; }

        // many to many relationship between students and meal plans, since this is a bridging table
        // use of foreign key - can add additional information
        [ForeignKey("Student")]
        public int student_id { get; set; }
        public virtual Student Student { get; set; }
        public bool StudentMealPlanHasPic { get; set; }
        public string PicExtension { get; set; }
        public string ImagePath { get; set; }

        [ForeignKey("MealPlan")]
        public int plan_id { get; set; }
        public virtual MealPlan MealPlan { get; set; }
    }
    public class StudentMealPlanDto
    {
        public int student_meal_plan_id { get; set; }

        public int student_id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }

        public int plan_id { get; set; }
        public string plan_name { get; set; }
        public bool StudentMealPlanHasPic { get; set; }
        public string PicExtension { get; set; }
    }
}

Test/Controllers/StudentMealPlanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using System.Diagnostics;
using Test.Models;
using Test.Models.ViewModels;
using System.Web.Script.Serialization;

namespace Test.Controllers
{
    public class StudentMealPlanController : Controller
    {
        private static readonly HttpClient client;
        private JavaScriptSerializer jss = new JavaScriptSerializer();

        static StudentMealPlanController()
        {
            HttpClientHandler handler = new HttpClientHandler()
            {
                AllowAutoRedirect = false,
                UseCookies = false
            };
            client = new HttpClient(handler);
            client.BaseAddress = new Uri("https://localhost:44326/api/");
        }

        private void GetApplicationCookie()
        {
            string token = "";
            client.DefaultRequestHeaders.Remove("Cookie");
            if (!User.Identity.IsAuthenticated) return;

            HttpCookie cookie = System.Web.HttpContext.Current.Request.Cookies.Get(".AspNet.ApplicationCookie");
            if (cookie != null) token = cookie.Value;
            Debug.WriteLine("Token Submitted is : " + token);
            if (token != "") client.DefaultRequestHeaders.Add("Cookie", ".AspNet.ApplicationCookie=" + token);

            return;
        }

        // GET: StudentMealPlan/List
        public ActionResult List()
           {
            //curl localhost:44326/api/StudentMealPlanData/ListStudentMealPlans 
            //objective: communicate with our StudentMealPlan data api to retrieve a list of StudentMealPlans

            string url = "StudentMealPlanData/ListStudentMealPlans";

            HttpResponseMessage response = client.GetAsync(url).Result;
            Debug.WriteLine(response.StatusCode);

            IEnumerable<StudentMealPlanDto> StudentMealPlans = response.Content.ReadAsAsync<IEnumerable<StudentMealPlanDto>>().Result;
            //Views/StudentMealPlan/List.cshtml

            return View(StudentMealPlans);
        }

        //GET: StudentMealPlan/Details/3
        public ActionResult Details(int id)
        {
            DetailsStudentMealPlan viewModel = new DetailsStudentMealPlan();
            //curl https://localhost:44326//api/StudentMealPlanData/ListStudentMealPlans/{id}

            string url = "StudentMealPlanData/ListStudentMealPlans/" + id;

            HttpResponseMessage response = client.GetAsync(url).Result;

            Debug.WriteLine("The response code is ");
            Debug.WriteLine(response.StatusCode);

            StudentMealPlanDto SelectedContent = response.Content.ReadAsAsync<StudentMealPlanDto>().Result;
            Debug.WriteLine("Student Meal Plan received ");
            Debug.WriteLine(SelectedContent.first_name);
            //Views/StudentMealPlan/Show.cshtml


            viewModel.SelectedStudentMealPlan = SelectedContent;

            url = "StudentMealPlanData/FindStudentMealPlan/" + id;
            response = client.GetAsync(url).Result;
            IEnumerable<StudentMealPlanDto> ResponsibleStudents = response.Content.ReadAsAsync<IEnumerable<StudentMealPlanDto>>().Result;

            viewModel.ResponsibleStudents = ResponsibleStudents;

            return View(viewModel);
        }


        // GET: StudentMealPlan/New
        public ActionResult New()
        {
            string url = "StudentMealPlanData/ListStudentMealPlans";
            HttpResponseMessage response = client.GetAsync(url).Result;
            IEnumerable<Models.StudentMealPlanDto> studentMealPlanOptions = response.Content.ReadAsAsync<IEnumerable<Models.StudentMealPlanDto>>().Result;
            return View(studentMealPlanOptions);
        }

        // POST: StudentMealPlan/Create
        [HttpPost]
        public ActionResult Create(Models.StudentMealPlan studentMealPlan)
        {
            Debug.WriteLine("The JSON payload is:");
            Debug.WriteLine(studentMealPlan.student_meal_plan_id);

            // Add StudentMealPlan to api
            string url = "StudentMealPlanData/AddStudentMealPlan/";

            string jsonPayload = jss.Serialize(studentMealPlan);
            Debug.WriteLine(jsonPayload);

            HttpContent content = new StringContent(jsonPayload);
            content.Headers.ContentType.MediaType = "application/json";

            HttpResponseMessage response = client.PostAsync(url, content).Result;

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("List");
            }
            else
            {
                return RedirectToAction("Error");
            }
        }

        //GET: StudentMealPlan/Edit/1
        public ActionResult Edit(int id)
        {
            string url = "StudentMealPlanData/FindStudentMealPlan/" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;
            StudentMealPlanDto SelectedStudentMealPlan = response.Content.ReadAsAsync<StudentMealPlanDto>().Result;
            return View(SelectedStudentMealPlan);
        }
        //POST: StudentMealPlan/Update/6
        [HttpPost]
        [Authorize]
        public ActionResult Update(int id, Models.StudentMealPlan StudentMealPlan, HttpPostedFileBase StudentMealPlanHasPic)
        {
            GetApplicationCookie();
            string url = "studentmealplandata/updatestudentmealplan/" + id;
            string jsonpayload = jss.Serialize(StudentMealPlan);
            HttpContent content = new StringContent(jsonpayload);
            content.Headers.ContentType.MediaType = "application/json";
            HttpResponseMessage response = client.PostAsync(url, content).Result;
            Debug.WriteLine(content);
            if (response.IsSuccessStatusCode && StudentMealPlanHasPic != null)
            {
                Debug.WriteLine("Calling Update Image method.");
                url = "StudentMealPlan/UploadStudentMealPlanPic" + id;
                MultipartFormDataContent requestcontent = new MultipartFormDataContent();
                HttpContent imagecontent = new StreamContent(StudentMealPlanHasPic.InputStream);
                requestcontent.Add(imagecontent, "StudentMealPlanPic", StudentMealPlanHasPic.FileName);
                response = client.PostAsync(url, requestcontent).Result;
                return RedirectToAction("List");
            }
            else if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("List");
            }
            {
                return RedirectToAction("Error");
            }
        }

        // GET: StudentMealPlan/Delete/5
        [Authorize]
        public ActionResult DeleteConfirm(int id)
        {
            string url = "StudentMealPlanData/FindStudentMealPlan" + id;
            HttpResponseMessage response = client.GetAsync(url).Result;
            StudentMealPlanDto selectedstudentmealplan = response.Content.ReadAsAsync<StudentMealPlanDto>().Result;
            return View(selectedstudentmealplan);
        }

        //POST: Diary/Delete/5
        [HttpPost]
        [Authorize]
        public ActionResult Delete(int id)
        {
            GetApplicationCookie();
            string url = "studentmealplandata/deletestudentmealplan" + id;
            HttpContent content = new StringContent("");
            content.Headers.ContentType.MediaType = "application/json";
            HttpResponseMessage response = client.PostAsync(url, content).Result;

            if (response.IsSuccessStatusCode)
            {
                return RedirectToAction("List");
            }
            else
            {
                return RedirectToAction("Error");
            }

        }

    }
}

Test/Views/StudentMealPlan/DeleteConfirm.cshtml
@model Test.Models.StudentMealPlanDto
@{
    ViewBag.Title = "DeleteConfirm";
}

<h2>Are you sure you want to delete this meal plan?</h2>
<a href="/StudentMealPlan/List">Cancel</a>
<h2>@Model.first_name</h2>
<div>
    Meal plan: @Model.plan_name
</div>

<form action="/Delete/@Model.student_meal_plan_id" method="POST">
    <input type="submit" value="Confirm Delete" />
</form>

Test/Views/StudentMealPlan/Details.cshtml
@model Test.Models.ViewModels.DetailsStudentMealPlan
@{
    ViewBag.Title = "Details StudentMealPlan";
}

<h2>Show Student Meal Plan</h2>
<p><a href="/StudentMealPlan/List">Go back to List</a></p>
<p><a href="/StudentMealPlan/Edit/@Model.SelectedStudentMealPlan.student_meal_plan_id"></a></p>
<p>First name: @Model.SelectedStudentMealPlan.first_name</p>
<p>Last name: @Model.SelectedStudentMealPlan.last_name</p>
<p>Meal plan: @Model.SelectedStudentMealPlan.plan_name</p>

<div>
    @{
    string imageurl = "/Content/Images/StudentMealPlan/default.jpg";
if (Model.SelectedStudentMealPlan.StudentMealPlanHasPic){
imageurl = "/Content/Images/StudentMealPlan" + Model.SelectedStudentMealPlan.StudentMealPlanID + "."+ Model.SelectedStudentMealPlan.PicExtension;
}}
</div>

<div>
    <img style="display:block; max-width:100%;" alt="@Model.SelectedStudentMealPlan.first_name" src="@imageurl"/>
</div>

Test/Views/StudentMealPlan/Edit.cshtml
﻿@model Test.Models.ViewModels.UpdateStudentMealPlan
    @{
        ViewBag.Title = "Edit";
    }

    <h2>Update Student Meal Plan</h2>
    <form action="/Update/@Model.SelectedStudentMealPlan.student_meal_plan_id" method="POST">

        <div>
            <label>First name:</label> <input type="text" name="fname" value="@Model.SelectedStudentMealPlan.first_name" />
        </div>

        <div>
            <label>Last name:</label> <input type="text" name="lname" value="@Model.SelectedStudentMealPlan.last_name" />
        </div>

        <div>
            <label>Meal Plan: </label> <input type="text" name="meal_plan" value="@Model.SelectedStudentMealPlan.plan_name" />
        </div>
        <div>
            <input type="file" name="StudentMealPlanHasPic"/>
        </div>
        <div>
            <input type="submit" value="Update Student Meal Plan"/>
        </div>
    </form>
   

Test/Views/StudentMealPlan/Index.cshtml
@{
    ViewBag.Title = "Manage Student Meal Plans";
}

<!DOCTYPE html>
<html>
<head>
    <title>Manage Student Meal Plans</title>
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" rel="stylesheet" />
    <style>
        body {
            font-family: Arial, sans-serif;
        }

        .main-container {
            margin-top: 50px;
        }

        .card {
            margin: 20px 0;
        }
    </style>
</head>
<body>
    <div class="container main-container">
        <div class="text-center">
            <h1 class="display-4">Manage Student Meal Plans</h1>
            <p class="lead">Create, edit, and view student meal plans efficiently!</p>
        </div>

        <div class="row">
            <div class="col-md-4">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Student Meal Plans</h5>
                        <p class="card-text">View all student meal plans.</p>
                        <a href="@Url.Action("List", "StudentMealPlan")" class="btn btn-primary">View Student Meal Plans</a>
                    </div>
                </div>
            </div>

            <div class="col-md-4">
                <div class="card">
                    <div class="card-body">
                        <h5 class="card-title">Create New Student Meal Plan</h5>
                        <p class="card-text">Create a new student meal plan.</p>
                        <a href="@Url.Action("New", "StudentMealPlan")" class="btn btn-primary">Create New Student Meal Plan</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
</body>
</html>

Test/Views/StudentMealPlan/List.cshtml
@model IEnumerable<Test.Models.StudentMealPlanDto>
@{
    ViewBag.Title = "List";
}

<h2>List</h2>


@foreach (var StudentMealPlan in Model)
{
    <div>
        <a href="Details/@StudentMealPlan.student_meal_plan_id">@StudentMealPlan.first_name @StudentMealPlan.last_name</a>
    </div>
}

Test/Views/StudentMealPlan/New.cshtml
@model IEnumerable<Test.Models.StudentMealPlanDto>
@{
    ViewBag.Title = "Create";
}

<h2>Add Student Meal  Plan</h2>
<form method="POST" action="Create" name="StudentMealPlanForm">


    <div>
        <label for="first_name">First Name:</label>
        <input type="text" name="first_name" id="first_name" /><span id="addfNameRequire"></span>
    </div>

    <div>
        <label for="last_name">Lasts Name:</label>
        <input type="text" name="last_name" id="last_name" /><span id="addlNameRequire"></span>
    </div>

    <div>
        <label for="plan_name">Plan Name:</label>
        <input type="text" name="plan_name" id="plan_name"><span id="addMealRequire"></span>
    </div>

    <div>
        <input type="submit" value="Add your meal plan" />
    </div>
</form>

<!--This Js doesn't allow empty forms.-->
<script>
    window.onload = function () {
        const formHandle = document.forms.StudentMealPlanForm;
        const firstName = document.getElementById("first_name");
        const lastName = document.getElementById("last_name");
        const planName = document.getElementById("plan_name");
        const addfName = document.getElementById("addfNameRequire");
        const addlName = document.getElementById("addlNameRequire");
        const addmeal = document.getElementById("addMealRequire");
        formHandle.onsubmit = function () {
            var valid = true;
            const fNameValue = formHandle.first_name.value;
            const lNameValue = formHandle.last_name.value;
            const mealValue = formHandle.plan_name.value;
            if (fNameValue === "") {
                firstName.style.background = "red";
                firstName.focus();
                addfName.innerHTML = "First Name is required.";
                valid = false;
            }

            if (lNameValue === "") {
                lastName.style.background = "red";
                lastName.focus();
                addlName.innerHTML = "Last Name is required.";
                valid = false;
            }

            if (mealValue === "") {
                planName.style.background = "red";
                planName.focus();
                addmeal.innerHTML = "Meal plan is required.";
                valid = false;
            }

            return valid;
        }
    }


</script>